project:
  type: website
  output-dir: _site
  render:
      - "*.qmd"  
      - "!slides/" 
      - "!psets/"

website:
  title: "PoliSci 813"
  description: "Graduate course in causal inference methods for political science"
  site-url: https://astrezhnev.github.io/ps813/
  repo-url: https://github.com/astrezhnev/ps813

  navbar:
    background: "#c5050c"  # UW-Madison red
    foreground: white
    left:
      - text: "Syllabus"
        href: syllabus.qmd
      - text: "Schedule"
        href: schedule.qmd
      - text: "Staff"
        href: staff.qmd
      - text: "Lectures"
        href: lectures.qmd
      - text: "Assignments"
        href: assignments.qmd
      - text: "Resources"
        href: resources.qmd
      - text: "Ed"
        href: https://edstem.org/us/courses/93768/
      - text: "Gradescope"
        href: https://www.gradescope.com/courses/1223529
    right:
      - icon: github
        href: https://github.com/astrezhnev/ps813
        aria-label: GitHub

  page-footer:
    left: |
      Licensed under a {{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}} [Creative Commons Attribution-NonCommercial 4.0 International License (CC BY-NC 4.0)](https://creativecommons.org/licenses/by-nc/4.0/).
    center: ""
    right: |
      Made with [Quarto](https://quarto.org/) | [Report an Issue](https://github.com/astrezhnev/ps813/issues)

format:
  html:
    theme:
      - cosmo
      - styles.scss
    css: styles.css
    toc: true
    toc-depth: 3
